[package]
name = "libnode_rs"
version = "0.0.2"
authors = ["alshdavid"]
repository = "https://github.com/alshdavid/libnode"
description = "Library embedding Nodejs (libnode) within Rust"
edition = "2021"
license = "MIT"

[lib]

[dependencies]
libloading = "^0.8.0"
libffi = "^4.0.0"